2021-05-24 18:24:05.280 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => insert,message => nil,module => ets,reason => nil},[{ets,insert,[],[]},{'Elixir.Api.DB.UserRepository',add,1,[{file,"lib/db/user_repository.ex"},{line,3}]},{'Elixir.Api.Router','-do_match/4-fun-3-',2,[{file,"lib/api_test/router.ex"},{line,72}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},...]},...]},...},...},...}
2021-05-24 18:24:05.392 [error] <0.522.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.521.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => insert,message => nil,module => ets,reason => nil},[{ets,insert,[],[]},{'Elixir.Api.DB.UserRepository',add,1,[{file,"lib/db/user_repository.ex"},{line,3}]},{'Elixir.Api.Router','-do_match/4-fun-3-',2,[{file,"lib/api_test/router.ex"},{line,72}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{...}]},...]},...},...}
2021-05-24 18:26:17.706 [error] <0.516.0> CRASH REPORT Process <0.516.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{ets,insert,[users,{<<"ee888ead-8684-4ce7-864c-9f258a968936">>,#{'__struct__' => 'Elixir.Api.Models.User',id => <<"ee888ead-8684-4ce7-864c-9f258a968936">>,name => <<"wow">>,password => <<"admin">>}}],[]},{'Elixir.Api.DB.UserRepository',add,1,[{file,"lib/db/user_repository.ex"},{line,3}]},{'Elixir.Api.Router','-do_match/4-fun-3-',2,[{file,"lib/api_test/router.ex"},{line,72}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-24 18:26:17.710 [error] <0.516.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.515.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{ets,insert,[users,{<<"ee888ead-8684-4ce7-864c-9f258a968936">>,#{'__struct__' => 'Elixir.Api.Models.User',id => <<"ee888ead-8684-4ce7-864c-9f258a968936">>,name => <<"wow">>,password => <<"admin">>}}],[]},{'Elixir.Api.DB.UserRepository',add,1,[{file,"lib/db/user_repository.ex"},{line,3}]},{'Elixir.Api.Router','-do_match/4-fun-3-',2,[{file,"lib/api_test/router.ex"},{line,72}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-24 19:24:35.166 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,109}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/De..."},...]},...]},...},...},...}
2021-05-24 19:24:35.169 [error] <0.524.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.520.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,109}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desk..."},...]},...]},...},...}
2021-05-24 19:27:39.473 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => assign,message => nil,term => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"4fa50575-7029-4825-8ee2-d...">>,...},...}},...}},...},...},...},...}
2021-05-24 19:27:39.475 [error] <0.522.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.517.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => assign,message => nil,term => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"4fa50575-7029-4825-8ee2-dc6...">>,...},...}},...}},...},...},...}
2021-05-24 19:28:58.695 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => assign,message => nil,term => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"fa240ae6-5c0d-41b1-ab1f-e...">>,...},...}},...}},...},...},...},...}
2021-05-24 19:28:58.698 [error] <0.518.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => assign,message => nil,term => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"fa240ae6-5c0d-41b1-ab1f-efa...">>,...},...}},...}},...},...},...}
2021-05-24 19:30:09.993 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,109}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/De..."},...]},...]},...},...},...}
2021-05-24 19:30:09.996 [error] <0.518.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,109}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desk..."},...]},...]},...},...}
2021-05-24 19:32:02.820 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/De..."},...]},...]},...},...},...}
2021-05-24 19:32:02.822 [error] <0.518.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desk..."},...]},...]},...},...}
2021-05-24 19:32:46.126 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/De..."},...]},...]},...},...},...}
2021-05-24 19:32:46.126 [error] <0.522.0> Cowboy stream 5 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desk..."},...]},...]},...},...}
2021-05-24 19:37:51.780 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/De..."},...]},...]},...},...},...}
2021-05-24 19:37:51.783 [error] <0.518.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desk..."},...]},...]},...},...}
2021-05-24 19:47:50.597 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/De..."},...]},...]},...},...},...}
2021-05-24 19:47:50.607 [error] <0.525.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.521.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => claims,message => nil,term => #{}},[{'Elixir.Api.Router','-do_match/4-fun-5-',2,[{file,"lib/api_test/router.ex"},{line,110}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desk..."},...]},...]},...},...}
2021-05-24 19:51:41.053 [error] <0.520.0> CRASH REPORT Process <0.520.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => validate_token,message => nil,module => 'Elixir.Api.Service.Auth',reason => nil},[{'Elixir.Api.Service.Auth',validate_token,[<0.521.0>,<<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE4Nzg2NzcsImlhdCI6MTYyMTg3NTA3NywiaWQiOiJkZWNlMWI2Mi0wYzVkLTQ5NmYtYmFmYy1kYzhmNjAzNGFhNGYiLCJhdWQiOiJKb2tlbiIsImV4cCI6MTYyMTg4MjI3NywiaWF0IjoxNjIxODc1MDc3LCJpc3MiOiJKb2tlbiIsImp0aSI6IjJxMTB0aWd1YXJ1bzFuZz...">>],...},...]},...},...},...}
2021-05-24 19:51:41.055 [error] <0.520.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => validate_token,message => nil,module => 'Elixir.Api.Service.Auth',reason => nil},[{'Elixir.Api.Service.Auth',validate_token,[<0.521.0>,<<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE4Nzg2NzcsImlhdCI6MTYyMTg3NTA3NywiaWQiOiJkZWNlMWI2Mi0wYzVkLTQ5NmYtYmFmYy1kYzhmNjAzNGFhNGYiLCJhdWQiOiJKb2tlbiIsImV4cCI6MTYyMTg4MjI3NywiaWF0IjoxNjIxODc1MDc3LCJpc3MiOiJKb2tlbiIsImp0aSI6IjJxMTB0aWd1YXJ1bzFuZzhq...">>],...},...]},...},...}
2021-05-24 19:53:59.635 [error] <0.522.0> gen_server <0.522.0> terminated with reason: {badkey,id,#{token => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE4Nzg4MzIsImlhdCI6MTYyMTg3NTIzMiwiaWQiOiI5YjU4OWUwMS1lZTMxLTQ2MjUtYmZjNi02N2Y2ZTUwMWUyMjAiLCJhdWQiOiJKb2tlbiIsImV4cCI6MTYyMTg4MjQzMiwiaWF0IjoxNjIxODc1MjMyLCJpc3MiOiJKb2tlbiIsImp0aSI6IjJxMTB0cmo1dHUwODFpZ3B2YzAwMDAwMyIsIm5iZiI6MTYyMTg3NTIzMn0.5loN1vmJxWT3L3idEod0O3S_O17U8_gFg5ySwa6EdxI">>}} in 'Elixir.Api.Service.Auth':handle_call/3 line 54
2021-05-24 19:53:59.656 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 2 neighbours crashed with reason: {badkey,id,#{token => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE4Nzg4MzIsImlhdCI6MTYyMTg3NTIzMiwiaWQiOiI5YjU4OWUwMS1lZTMxLTQ2MjUtYmZjNi02N2Y2ZTUwMWUyMjAiLCJhdWQiOiJKb2tlbiIsImV4cCI6MTYyMTg4MjQzMiwiaWF0IjoxNjIxODc1MjMyLCJpc3MiOiJKb2tlbiIsImp0aSI6IjJxMTB0cmo1dHUwODFpZ3B2YzAwMDAwMyIsIm5iZiI6MTYyMTg3NTIzMn0.5loN1vmJxWT3L3idEod0O3S_O17U8_gFg5ySwa6EdxI">>}} in 'Elixir.Api.Service.Auth':handle_call/3 line 54
2021-05-24 19:53:59.658 [error] <0.520.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.516.0> had its request process exit with reason: {badkey,id,#{token => <<"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE4Nzg4MzIsImlhdCI6MTYyMTg3NTIzMiwiaWQiOiI5YjU4OWUwMS1lZTMxLTQ2MjUtYmZjNi02N2Y2ZTUwMWUyMjAiLCJhdWQiOiJKb2tlbiIsImV4cCI6MTYyMTg4MjQzMiwiaWF0IjoxNjIxODc1MjMyLCJpc3MiOiJKb2tlbiIsImp0aSI6IjJxMTB0cmo1dHUwODFpZ3B2YzAwMDAwMyIsIm5iZiI6MTYyMTg3NTIzMn0.5loN1vmJxWT3L3idEod0O3S_O17U8_gFg5ySwa6EdxI">>}} in 'Elixir.Api.Service.Auth':handle_call/3 line 54
2021-05-24 19:58:17.215 [error] <0.519.0> CRASH REPORT Process <0.519.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => {ok,#{aud => <<"Joken">>,exp => 1621879090,iat => 1621875490,id => <<"d8aeab80-ed3f-4b88-bc16-7147e1e3542a">>,iss => <<"Joken">>,jti => <<"2q10uaj4nn000m1a140000c6">>,nbf => 1621875490}}},[{'Elixir.Api.AuthPlug',call,2,[{file,"lib/api_test/plugs/validate_token.ex"},{line,18}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/p..."},...]},...]},...},...},...}
2021-05-24 19:58:17.217 [error] <0.519.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.515.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => {ok,#{aud => <<"Joken">>,exp => 1621879090,iat => 1621875490,id => <<"d8aeab80-ed3f-4b88-bc16-7147e1e3542a">>,iss => <<"Joken">>,jti => <<"2q10uaj4nn000m1a140000c6">>,nbf => 1621875490}}},[{'Elixir.Api.AuthPlug',call,2,[{file,"lib/api_test/plugs/validate_token.ex"},{line,18}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plu..."},...]},...]},...},...}
2021-05-24 20:00:50.668 [error] <0.519.0> CRASH REPORT Process <0.519.0> with 2 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => ok},[{'Elixir.Api.Router','-do_match/4-fun-7-',2,[{file,"lib/api_test/router.ex"},{line,111}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desktop/rabbit/deps/cowboy/src..."},...]},...]},...},...},...}
2021-05-24 20:00:50.674 [error] <0.519.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.515.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.MatchError',term => ok},[{'Elixir.Api.Router','-do_match/4-fun-7-',2,[{file,"lib/api_test/router.ex"},{line,111}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/Raul/Desktop/rabbit/deps/cowboy/src/c..."},...]},...]},...},...}
