2021-05-23 14:46:17.473 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => publish,message => nil,module => 'Elixir.EventPublisher',reason => nil},[{'Elixir.EventPublisher',publish,[<<"api.login.auth-login.events">>,{<<"1">>,<<"admin">>}],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,36}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_tes..."},...]},...]},...},...},...}
2021-05-23 14:46:17.509 [error] <0.577.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.576.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => publish,message => nil,module => 'Elixir.EventPublisher',reason => nil},[{'Elixir.EventPublisher',publish,[<<"api.login.auth-login.events">>,{<<"1">>,<<"admin">>}],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,36}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/..."},...]},...]},...},...}
2021-05-23 14:46:54.236 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => {<<"1">>,<<"admin">>}},[{'Elixir.Poison.Encoder.Any',encode,2,[{file,"lib/poison/encoder.ex"},{line,383}]},{'Elixir.Poison','encode!',2,[{file,"lib/poison.ex"},{line,41}]},{'Elixir.Api.Service.Publisher',publish,3,[{file,"lib/services/publisher.ex"},{line,10}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,36}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib..."},...]},...]},...},...},...}
2021-05-23 14:46:54.267 [error] <0.498.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.497.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => {<<"1">>,<<"admin">>}},[{'Elixir.Poison.Encoder.Any',encode,2,[{file,"lib/poison/encoder.ex"},{line,383}]},{'Elixir.Poison','encode!',2,[{file,"lib/poison.ex"},{line,41}]},{'Elixir.Api.Service.Publisher',publish,3,[{file,"lib/services/publisher.ex"},{line,10}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,36}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/p..."},...]},...]},...},...}
2021-05-23 14:47:41.323 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => {<<"1">>,<<"admin">>}},[{'Elixir.Poison.Encoder.Any',encode,2,[{file,"lib/poison/encoder.ex"},{line,383}]},{'Elixir.Poison','encode!',2,[{file,"lib/poison.ex"},{line,41}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,38}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_te..."},...]},...]},...},...},...}
2021-05-23 14:47:41.327 [error] <0.498.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.497.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => {<<"1">>,<<"admin">>}},[{'Elixir.Poison.Encoder.Any',encode,2,[{file,"lib/poison/encoder.ex"},{line,383}]},{'Elixir.Poison','encode!',2,[{file,"lib/poison.ex"},{line,41}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,38}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test..."},...]},...]},...},...}
2021-05-23 14:48:43.335 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 3,function => publish,message => nil,module => 'Elixir.EventBus',reason => nil},[{'Elixir.EventBus',publish,[<<"api.login.auth-login.events">>,<<"{\"name\":\"admin\",\"id\":\"1\"}">>,[{app_id,<<"auth_service">>},{content_type,<<"application/json">>},{persistent,true}]],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,36}]},{'Elixir.Api.Router',dispatch,2,[{file,"li..."},...]},...]},...},...},...}
2021-05-23 14:48:43.385 [error] <0.498.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.497.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 3,function => publish,message => nil,module => 'Elixir.EventBus',reason => nil},[{'Elixir.EventBus',publish,[<<"api.login.auth-login.events">>,<<"{\"name\":\"admin\",\"id\":\"1\"}">>,[{app_id,<<"auth_service">>},{content_type,<<"application/json">>},{persistent,true}]],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,36}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/..."},...]},...]},...},...}
2021-05-23 14:49:25.011 [error] <0.499.0> CRASH REPORT Process <0.499.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.38358890>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"p...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 14:49:25.014 [error] <0.499.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.498.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.38358890>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"pos...">> => ...,...},...}},...},...]}},...}
2021-05-23 14:49:42.472 [error] <0.501.0> CRASH REPORT Process <0.501.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.38358890>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"p...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 14:49:42.472 [error] <0.501.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.498.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.38358890>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"pos...">> => ...,...},...}},...},...]}},...}
2021-05-23 14:51:42.634 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.133089409>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 14:51:42.664 [error] <0.505.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.504.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.133089409>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"po...">> => ...,...},...}},...},...]}},...}
2021-05-23 14:54:30.475 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.3309381>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"po...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 14:54:30.490 [error] <0.505.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.504.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.3309381>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"post...">> => ...,...},...}},...},...]}},...}
2021-05-23 14:54:58.997 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.105923794>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 14:54:59.001 [error] <0.505.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.504.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.105923794>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"po...">> => ...,...},...}},...},...]}},...}
2021-05-23 15:00:05.395 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.84346287>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"p...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 15:00:05.417 [error] <0.505.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.504.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.84346287>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"pos...">> => ...,...},...}},...},...]}},...}
2021-05-23 15:03:23.135 [error] <0.388.0> CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Api.Service.EventPublisher was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-05-23 15:03:41.598 [error] <0.388.0> CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Api.Service.Publisher was given as a child to a supervisor\nbut it does not implement child_spec/1.\n\nIf you own the given module, please define a child_spec/1 function\nthat receives an argument and returns a child specification as a map.\nFor example:\n\n    def child_spec(opts) do\n      %{\n        id: __MODULE__,\n        start: {__MODULE__, :start_link, [opts]},\n        type: :worker,\n        restart: :perm...">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-05-23 15:04:27.314 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Api.Service.Publisher was given as a child to a supervisor\nbut it does not implement child_spec/1.\n\nIf you own the given module, please define a child_spec/1 function\nthat receives an argument and returns a child specification as a map.\nFor example:\n\n    def child_spec(opts) do\n      %{\n        id: __MODULE__,\n        start: {__MODULE__, :start_link, [opts]},\n        type: :worker,\n        restart: :perm...">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-05-23 15:04:49.096 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:04:49.097 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:06:01.013 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:06:01.013 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:06:17.299 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Api.Service.Publisher was given as a child to a supervisor\nbut it does not implement child_spec/1.\n\nIf you own the given module, please define a child_spec/1 function\nthat receives an argument and returns a child specification as a map.\nFor example:\n\n    def child_spec(opts) do\n      %{\n        id: __MODULE__,\n        start: {__MODULE__, :start_link, [opts]},\n        type: :worker,\n        restart: :perm...">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-05-23 15:07:26.775 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:07:26.775 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:08:12.323 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:08:12.323 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:09:04.899 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason ok in context start_error
2021-05-23 15:09:04.899 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',ok}},{'Elixir.ApiTest.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-05-23 15:09:33.307 [error] <0.392.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:09:33.307 [error] <0.390.0> CRASH REPORT Process <0.390.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:09:49.027 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:09:49.027 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:11:22.889 [error] <0.503.0> CRASH REPORT Process <0.503.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => start_link,message => nil,module => 'Elixir.Api.Service.Publisher',reason => nil},[{'Elixir.Api.Service.Publisher',start_link,[],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,33}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',...},...]},...},...},...}
2021-05-23 15:11:22.915 [error] <0.503.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.502.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => start_link,message => nil,module => 'Elixir.Api.Service.Publisher',reason => nil},[{'Elixir.Api.Service.Publisher',start_link,[],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,33}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',...},...]},...},...}
2021-05-23 15:12:46.985 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => start_link,message => nil,module => 'Elixir.Api.Service.Publisher',reason => nil},[{'Elixir.Api.Service.Publisher',start_link,[],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,33}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',...},...]},...},...},...}
2021-05-23 15:12:46.994 [error] <0.505.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.504.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => start_link,message => nil,module => 'Elixir.Api.Service.Publisher',reason => nil},[{'Elixir.Api.Service.Publisher',start_link,[],[]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,33}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',...},...]},...},...}
2021-05-23 15:13:38.595 [error] <0.505.0> CRASH REPORT Process <0.505.0> with 1 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not a bitstring\n">>},[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,33}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-23 15:13:38.601 [error] <0.505.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.504.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not a bitstring\n">>},[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,33}]},{'Elixir.Api.Router',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-23 15:14:14.542 [error] <0.396.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Api.Service.Publisher',start_link,[[{app_id,api_test}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,...}]}} in context start_error
2021-05-23 15:14:14.542 [error] <0.394.0> CRASH REPORT Process <0.394.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{undef,[{'Elixir.Api.Service.Publisher',start_link,[[{app_id,api_test}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:14:30.390 [error] <0.392.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:14:30.390 [error] <0.390.0> CRASH REPORT Process <0.390.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:15:13.357 [error] <0.378.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:15:13.357 [error] <0.376.0> CRASH REPORT Process <0.376.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:15:20.395 [error] <0.392.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Api.Service.Publisher',start_link,[[{app_id,api_test}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,...}]}} in context start_error
2021-05-23 15:15:20.395 [error] <0.390.0> CRASH REPORT Process <0.390.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{undef,[{'Elixir.Api.Service.Publisher',start_link,[[{app_id,api_test}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:15:35.570 [error] <0.392.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link([{app_id,api_test}]) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:15:35.570 [error] <0.390.0> CRASH REPORT Process <0.390.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:16:13.852 [error] <0.390.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Helios.Service.EventPublisher' started with 'Elixir.Helios.Service.EventPublisher':start_link({app_id,helios}) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Helios.Service.EventPublisher',start_link,[{app_id,helios}],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},...]}} in context start_error
2021-05-23 15:16:13.853 [error] <0.388.0> CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Helios.Service.EventPublisher',{'EXIT',{undef,[{'Elixir.Helios.Service.EventPublisher',start_link,[{app_id,helios}],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:16:24.372 [error] <0.390.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link({app_id,helios}) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:16:24.372 [error] <0.388.0> CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:16:56.918 [error] <0.398.0> Supervisor 'Elixir.ApiTest.Supervisor' had child 'Elixir.Api.Service.Publisher' started with 'Elixir.Api.Service.Publisher':start_link({app_id,helios}) at undefined exit with reason {'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2021-05-23 15:16:56.918 [error] <0.396.0> CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Service.Publisher',{'EXIT',{badarg,[{erlang,byte_size,[nil],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',start,2,[{file,"lib/services/publisher.ex"},{line,2}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"superv..."},...]},...]}}}},...} in application_master:init/4 line 142
2021-05-23 15:24:03.202 [error] <0.515.0> CRASH REPORT Process <0.515.0> with 2 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,'++',[#{id => <<"1">>,name => <<"admin">>},[{app_id,<<"auth_service">>},{content_type,<<"application/json">>},{persistent,true}]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',publish,3,[{file,"lib/services/publisher.ex"},{line,11}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,37}]},{'Elixir.Api.Router',dispatch,...},...]},...},...},...}
2021-05-23 15:24:03.207 [error] <0.515.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.514.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,'++',[#{id => <<"1">>,name => <<"admin">>},[{app_id,<<"auth_service">>},{content_type,<<"application/json">>},{persistent,true}]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Api.Service.Publisher',publish,3,[{file,"lib/services/publisher.ex"},{line,11}]},{'Elixir.Api.Router','-do_match/4-fun-1-',2,[{file,"lib/api_test/router.ex"},{line,37}]},{'Elixir.Api.Router',dispatch,...},...]},...},...}
2021-05-23 15:25:46.405 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 2 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.84346287>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"p...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 15:25:46.409 [error] <0.498.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.497.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.84346287>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"pos...">> => ...,...},...}},...},...]}},...}
2021-05-23 15:28:33.757 [error] <0.510.0> CRASH REPORT Process <0.510.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.84346287>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"p...">> => ...,...},...}},...},...]}},...},...}
2021-05-23 15:28:33.761 [error] <0.510.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.509.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[event_bus_helper_state,{get,#Fun<Elixir.Api.Helpers.EventBus.0.84346287>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"pos...">> => ...,...},...}},...},...]}},...}
2021-05-23 15:30:40.750 [error] <0.395.0>@Elixir.Api.Service.EventPublisher:start CRASH REPORT Process <0.395.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Api.Service.EventPublisher':start() in application_master:init/4 line 142
2021-05-23 15:31:01.898 [error] <0.388.0>@Elixir.Api.Service.Publisher:start:2 CRASH REPORT Process <0.388.0> with 0 neighbours exited with reason: bad argument in call to erlang:byte_size(nil) in 'Elixir.Api.Service.Publisher':start/2 line 2 in application_master:init/4 line 142
2021-05-23 15:31:37.401 [error] <0.396.0>@Elixir.Api.Service.Publisher:start:2 CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: bad argument in call to erlang:byte_size(nil) in 'Elixir.Api.Service.Publisher':start/2 line 2 in application_master:init/4 line 142
2021-05-23 15:32:15.316 [error] <0.396.0>@Elixir.Api.Service.Publisher:start:2 CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: bad argument in call to erlang:byte_size(nil) in 'Elixir.Api.Service.Publisher':start/2 line 2 in application_master:init/4 line 142
2021-05-23 15:32:23.196 [error] <0.396.0>@Elixir.Api.Service.Publisher:start:2 CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: bad argument in call to erlang:byte_size(nil) in 'Elixir.Api.Service.Publisher':start/2 line 2 in application_master:init/4 line 142
2021-05-23 15:33:13.015 [error] <0.396.0>@Elixir.Api.Service.Publisher:start:2 CRASH REPORT Process <0.396.0> with 0 neighbours exited with reason: no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.Api.Service.Publisher':start/2 line 2 in application_master:init/4 line 142
2021-05-23 16:07:27.052 [error] <0.509.0> gen_server <0.509.0> terminated with reason: {socket_error,timeout}
2021-05-23 16:07:27.052 [error] <0.503.0> gen_server <0.503.0> terminated with reason: {socket_error,timeout}
2021-05-23 16:07:27.123 [error] <0.509.0> CRASH REPORT Process <0.509.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2021-05-23 16:07:27.123 [error] <0.502.0> Supervisor {<0.502.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.503.0>, <0.507.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49434 -> 127.0.0.1:5672">>) at <0.509.0> exit with reason {socket_error,timeout} in context child_terminated
2021-05-23 16:07:27.124 [error] <0.502.0> Supervisor {<0.502.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.503.0>, <0.507.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49434 -> 127.0.0.1:5672">>) at <0.509.0> exit with reason reached_max_restart_intensity in context shutdown
2021-05-23 16:07:27.127 [error] <0.503.0> CRASH REPORT Process <0.503.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2021-05-23 16:07:27.127 [error] <0.501.0> Supervisor {<0.501.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.502.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.503.0> exit with reason {socket_error,timeout} in context child_terminated
2021-05-23 16:07:27.127 [error] <0.501.0> Supervisor {<0.501.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.502.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.503.0> exit with reason reached_max_restart_intensity in context shutdown
2021-05-23 19:09:30.360 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 1 neighbours exited with reason: {{{{noproc,{gen_server,call,[<0.514.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"admin\",\"id\":\"1\"}">>},<0.565.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}},...},...}
2021-05-23 19:09:30.367 [error] <0.565.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.564.0> had its request process exit with reason: {{{noproc,{gen_server,call,[<0.514.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"admin\",\"id\":\"1\"}">>},<0.565.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,...}},...},...]}},...}
2021-05-23 19:09:31.113 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 1 neighbours exited with reason: {{{{noproc,{gen_server,call,[<0.514.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"admin\",\"id\":\"1\"}">>},<0.567.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}},...},...}
2021-05-23 19:09:31.113 [error] <0.567.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.564.0> had its request process exit with reason: {{{noproc,{gen_server,call,[<0.514.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"admin\",\"id\":\"1\"}">>},<0.567.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,...}},...},...]}},...}
2021-05-23 19:10:34.063 [error] <0.521.0> CRASH REPORT Process <0.521.0> with 1 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,[bus_tate,{get,#Fun<Elixir.Api.Helpers.EventBus.0.30129231>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<...>>,...},...}},...},...]}},...},...}
2021-05-23 19:10:34.070 [error] <0.521.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.520.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,[bus_tate,{get,#Fun<Elixir.Api.Helpers.EventBus.0.30129231>},5000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"...">>,...},...}},...},...]}},...}
2021-05-23 19:37:49.058 [error] <0.510.0> gen_server <0.510.0> terminated with reason: {socket_error,timeout}
2021-05-23 19:37:49.061 [error] <0.504.0> gen_server <0.504.0> terminated with reason: {socket_error,timeout}
2021-05-23 19:37:49.123 [error] <0.510.0> CRASH REPORT Process <0.510.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2021-05-23 19:37:49.124 [error] <0.503.0> Supervisor {<0.503.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.504.0>, <0.508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58949 -> 127.0.0.1:5672">>) at <0.510.0> exit with reason {socket_error,timeout} in context child_terminated
2021-05-23 19:37:49.124 [error] <0.503.0> Supervisor {<0.503.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.504.0>, <0.508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:58949 -> 127.0.0.1:5672">>) at <0.510.0> exit with reason reached_max_restart_intensity in context shutdown
2021-05-23 19:37:56.021 [error] <0.504.0> CRASH REPORT Process <0.504.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2021-05-23 19:37:56.021 [error] <0.502.0> Supervisor {<0.502.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.503.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.504.0> exit with reason {socket_error,timeout} in context child_terminated
2021-05-23 19:37:56.021 [error] <0.502.0> Supervisor {<0.502.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.503.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.504.0> exit with reason reached_max_restart_intensity in context shutdown
2021-05-23 21:14:18.133 [error] <0.574.0> CRASH REPORT Process <0.574.0> with 1 neighbours exited with reason: {{{{noproc,{gen_server,call,[<0.515.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"admin\",\"id\":\"1\"}">>},<0.574.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => ...,...}},...},...]}},...},...}
2021-05-23 21:14:18.151 [error] <0.574.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.573.0> had its request process exit with reason: {{{noproc,{gen_server,call,[<0.515.0>,{call,{'basic.publish',0,<<"my_api">>,<<"api.login.auth-login.events">>,false,false},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,2,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,<<"auth_service">>,undefined},<<"{\"name\":\"admin\",\"id\":\"1\"}">>},<0.574.0>},70000]}},{'Elixir.Api.Router',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,...}},...},...]}},...}
2021-05-23 22:27:24.130 [error] <0.504.0> gen_server <0.504.0> terminated with reason: {socket_error,timeout}
2021-05-23 22:27:24.131 [error] <0.498.0> gen_server <0.498.0> terminated with reason: {socket_error,timeout}
2021-05-23 22:27:24.180 [error] <0.504.0> CRASH REPORT Process <0.504.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2021-05-23 22:27:24.180 [error] <0.497.0> Supervisor {<0.497.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.498.0>, <0.502.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61274 -> 127.0.0.1:5672">>) at <0.504.0> exit with reason {socket_error,timeout} in context child_terminated
2021-05-23 22:27:24.180 [error] <0.497.0> Supervisor {<0.497.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.498.0>, <0.502.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61274 -> 127.0.0.1:5672">>) at <0.504.0> exit with reason reached_max_restart_intensity in context shutdown
2021-05-23 22:27:30.575 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2021-05-23 22:27:30.575 [error] <0.496.0> Supervisor {<0.496.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.497.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.498.0> exit with reason {socket_error,timeout} in context child_terminated
2021-05-23 22:27:30.575 [error] <0.496.0> Supervisor {<0.496.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.497.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,2047,0,10,60000,...}) at <0.498.0> exit with reason reached_max_restart_intensity in context shutdown
